added showOnFocus prop & label + translation
orso-co/Orso.Arpa.Web pull request #100
Opened 2022-02-23 13:29 UTC by wolfgangroese

2022-03-05 18:48 UTC, VILLAN3LL3 requested changes

2022-03-05 18:48 UTC, VILLAN3LL3 commented on src/app/features/musician-profile-dialog/musician-layout/musician-layout.component.html
> +              header="{{'musician-profile-dialog.DOUBLING_INSTRUMENT' | translate }}"
Zum Setzen variabler Werte empfiehlt Google folgende Syntax zu verwenden: `[header]="'musician-profile-dialog.DOUBLING_INSTRUMENT' | translate"`

2022-03-05 18:48 UTC, VILLAN3LL3 commented on src/app/features/musician-profile-dialog/musician-layout/musician-layout.component.html
> +              header="{{'musician-profile-dialog.DOUBLING_INSTRUMENT' | translate }}"
Gilt auch für weitere, Analoge Stellen

2022-03-25 15:51 UTC, wolfgangroese commented on src/app/features/musician-profile-dialog/musician-layout/musician-layout.component.html
> +              header="{{'musician-profile-dialog.DOUBLING_INSTRUMENT' | translate }}"
done :-)

2022-03-25 15:52 UTC, wolfgangroese commented
das eigentliche FocusListener-Problem konnte ich zwar nicht lösen, aber da ist Sascha an anderer Stelle bereits dran.

2022-03-25 16:19 UTC, merged