make mupro-projects clickable for opendialog
orso-co/Orso.Arpa.Web pull request #102
Opened 2022-02-23 22:58 UTC by wolfgangroese

2022-03-01 11:52 UTC, wolfgangroese commented
@VILLAN3LL3  ich bekomme immer noch den Fehler "Cannot read properties of undefined (Reading participationStatusInner)" beim Aufruf des Dialogs. Du siehst sicher sofort an was das liegt, ich checks nicht, warum dieser Fehler passiert.. :-/ 

![CleanShot 2022-03-01 at 12 50 49](https://user-images.githubusercontent.com/4527954/156164271-6ddf7836-088e-4bf6-abbf-4b778306c7c0.png)

2022-03-05 18:46 UTC, VILLAN3LL3 requested changes, later dismissed

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/mupro.component.html
> +                <div class='city'>{{row.person.addresses.city}}</div>
kann mir grad nicht richtig vorstellen, dass das funktioniert, da addresses doch sicher ein array ist?

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/participation-dialog/participation-dialog.component.html
> +          [options]="(statusOptions$ | async)!"
participationstatus inner und internalt haben verschiedene wertemengen, daher müssen auch unterschiedliche options verwendet werden

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/participation-dialog/participation-dialog.component.ts
> +      participationStatusIdPerformer: [null, [Validators.required]],
ich würde immer soweit möglich die form controls gleich benennen wie die dto properties, dann kann man erstens einfacher das entsprechende dto daraus bauen und hat zweitens die möglichkeit, bei 422 fehlern die fehlermeldungen direkt am jeweiligen control anzuzeigen

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +          <!-- <div class="country">Deutschland, Berlin</div> -->
Ist das Kunst oder kann das weg? :)

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                <div class="p-col-12 section-detail" >
Ich denke nicht, dass ein Leerzeichen an dieser Stelle einen Mehrwert bringt

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +<!-- <arpa-mupro-details></arpa-mupro-details> -->
wird das noch benötigt?

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/projects/projects.component.ts
> +    { label: 'P-STATUS_P', property: 'projectParticipations.participationStatusInner.selectValue.name', type: 'text', show: true },
Ich rate von Abkürzungen wie "P-STATUS_P" ab, da jemand anderes (und im Zweifel auch man selbst nach einigen Wochen ;-)) nicht direkt versteht, was damit gemeint ist

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/projects/projects.component.ts
> +    // { label: 'STATE', property: 'stateId', type: 'state', stateTable: 'Project', show: true },
Auskommentierten Code bitte immer entfernen, wenn er nicht mehr benötigt wird

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/projects/projects.component.ts
> +  participations: ProjectParticipationDto [] = [];
Da gehört kein Leerzeichen zwischen ProjectParticipationDto und []

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/mupro/projects/projects.component.ts
> +    });
Sollte da nach dem Schließen des Dialogs nicht was passieren?

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/musician-profile-dialog/musician-profile-dialog.module.ts
> +    ],
?

2022-03-05 18:46 UTC, VILLAN3LL3 commented on src/app/features/profile/my-projects/my-projects.component.html
>          </div>
Warum eine Leerzeile?

2022-03-25 16:21 UTC, wolfgangroese commented on src/app/features/mupro/profiles/profiles.component.html
> +          <!-- <div class="country">Deutschland, Berlin</div> -->
das sind Reste von Sascha, das hau ich weg, das soll später ja aus AdressDto kommen

2022-03-25 17:38 UTC, wolfgangroese commented on src/app/features/mupro/mupro.component.html
> +                <div class='city'>{{row.person.addresses.city}}</div>
habs erst mal komplett rausgenommen, da noch kein plan wie mit array umgehen an der stelle.. ich versuch stattdessen preferred region zu verwenden, was ohnehin mehr sinn macht :-)

2022-03-25 17:40 UTC, wolfgangroese commented on src/app/features/mupro/participation-dialog/participation-dialog.component.html
> +          [options]="(statusOptions$ | async)!"
ok... ich hab was versucht.. mal sehen, ob ich das raffe..

2022-03-25 18:26 UTC, wolfgangroese commented on src/app/features/mupro/projects/projects.component.ts
> +    });
hmm.. da muss glaub noch das ref.onClose-Dings hin.. das hab ich nur noch nicht verstanden. baustelle ;-)

2022-03-25 18:31 UTC, wolfgangroese commented on src/app/features/profile/my-projects/my-projects.component.html
>          </div>
hab alle leerzeilen wieder raus.. ich hau die manchmal rein um struktur zu haben und überblick zu gewinnen.. ich lass das künftig :-)

2022-03-25 18:37 UTC, wolfgangroese commented
Aktueller Stand siehe: https://orsonauten.slack.com/archives/C01LEL24L4D/p1648228905323749

2022-05-06 10:53 UTC, sSeewald commented on src/app/features/mupro/projects-by-mupro/projects-by-mupro.component.html
> +<h1>projects by mupro component here!</h1>
@wolfgangroese Wird diese Komponente gebraucht oder ist das von einem Experiment? Wird momentan nirgends verwendet.

2022-05-06 10:57 UTC, wolfgangroese commented on src/app/features/mupro/projects-by-mupro/projects-by-mupro.component.html
> +<h1>projects by mupro component here!</h1>
das ist tatsächlich noch ein experiment, ich schau's mir gleich noch mal an und lösche es wahrscheinlich damits ordentlich is ,-)

2022-05-06 11:34 UTC, wolfgangroese reviewed
am 5.5. mit sascha weitergemacht, daher nicht noch mal reviewed von meiner seite.

2022-05-06 14:11 UTC, merged