refactoring form for staff creating mupros from person profiles dialog
orso-co/Orso.Arpa.Web pull request #188
Opened 2022-11-23 18:33 UTC by wolfgangroese

still WIP!

2022-11-24 17:03 UTC, VILLAN3LL3 requested changes

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/participation-dialog/participation-dialog.component.scss
> +  color: red;
Wie bereits im Slack erwähnt, empfehle ich, Farben aus der Color Palette des Themes zu verwenden

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                    <h2 style='padding-right: 1rem'
inline styles sollten vermieden werden. außerdem bietet primeng auch etliche vordefinierte styling Klassen, die verwendet werden können. In diesem Fall müsste es p-pr-3 oder so ähnlich sein

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                    <h2 style='padding-right: 1rem'
https://github.com/primefaces/primeflex/wiki/PrimeFlex-v2

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                  <div style='display:inline-flex'>
hier kann die Klasse p-d-inline-flex verwendet werden

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                      pTooltip="{{ 'musician-profile-dialog.LEVEL_ASSESSMENT_PERFORMER' | translate }}"
Angular empfiehlt bei sowas die Property Schreibweise: `[pTooltip]="'musician-profile-dialog.LEVEL_ASSESSMENT_PERFORMER' | translate"` Oder funktioniert das bei pTooltip nicht?

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                      style='padding-left: 1rem'
Hier die Klasse `p-pl-3` verwenden. Wobei ich gar nicht weiß, ob style und class bei der PrimeNg Komponente überhaupt funktioniert? Evtl. mit der styleClass Property arbeiten oder dem style Objekt

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                  <div style='display:inline-flex'>
class p-d-inline-flex

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                    style='padding-left: 1rem'
s.o.

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                  <div style='text-align: left'>
class p-text-left

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/mupro/projects/projects.component.ts
> +    { label: 'PARTICIPATIONSTATUS_STAFF', property: 'projectParticipations.participationStatusInternal', type: 'text', show: true, },
Ich kenne die Sascha-Tabelle nicht so gut, aber ich glaube nicht, dass das so funktioniert, weil participations vermutlich ein Array am Projekt Objekt ist und keine einfache Property

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/musician-profile-dialog/musician-instruments/musician-instruments.component.html
> +    {{'mupro.CREATE_NEW_MUPRO' | translate }}
Hier verwendest du mit `mupro` ein anderes translation prefix als im Rest der Komponente. Ist das so korrekt?

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/musician-profile-dialog/musician-instruments/musician-instruments.component.html
> +  <header *ngIf="isNew; else editHeader ">
Das Leerzeichen hinter `editHeader` kann weg

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/persons/person-dialog/person-profiles/person-profiles-musician/person-profiles-musician.component.ts
> +} from '../../../../musician-profile-dialog/musician-instruments/musician-instruments.component';
Kann bei den imports noch was aufgeräumt werden?

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/musician-profile-dialog/musician-instruments/musician-instruments.component.ts
>    public sections: Observable<SectionDto[]> = this.config.data.sections;
Hier wäre es empfehlenswert der Konvention zu folgen und Observables mit $-Präfix zu versehen, also: `sections$`

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/app/features/persons/person-dialog/person-profiles/person-profiles-musician/person-profiles-musician.component.ts
> +        profile: new BehaviorSubject({doublingInstruments: [],
Hier wäre es gut der Konvention zu folgen und BehaviorSubjects mit $$-Präfix zu versehen, also `profile$$`. Achtung, muss dann auch in src/app/features/musician-profile-dialog/musician-instruments/musician-instruments.component.ts angepasst werden.

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/assets/i18n/appointments/fr.json
> +
Warum so viele Leerzeilen?

2022-11-24 17:03 UTC, VILLAN3LL3 commented on src/assets/i18n/musician-profile-dialog/de.json
> +  "DEACTIVATION": "Deactivation",
Deaktivierung?

2022-11-24 23:43 UTC, wolfgangroese commented on src/app/features/mupro/profiles/profiles.component.html
> +                      pTooltip="{{ 'musician-profile-dialog.LEVEL_ASSESSMENT_PERFORMER' | translate }}"
ein scheint bei pTooltip tatsächlich nicht zu funktioniern. ich hab die Schreibweise übernommen aus vorhandenen analogen Stellen 😬 
<img width="1338" alt="CleanShot 2022-11-25 at 00 42 24@2x" src="https://user-images.githubusercontent.com/4527954/203875116-7cc24cd7-737b-4b7d-afab-fea93d5e7055.png">

2022-11-24 23:49 UTC, wolfgangroese commented on src/app/features/mupro/profiles/profiles.component.html
> +                      style='padding-left: 1rem'
bin mir auch nicht sicher, aber ergebniss schaut gut aus ,-)

2022-11-24 23:57 UTC, wolfgangroese commented on src/app/features/mupro/projects/projects.component.ts
> +    { label: 'PARTICIPATIONSTATUS_STAFF', property: 'projectParticipations.participationStatusInternal', type: 'text', show: true, },
genau DARÜBER bin ich heute auch gestolpert... das ist alles so krass verworren, ich möchte einreissen und neu machen. muss da noch tiefer nachdenken, was grad schwierig ist auf holpriger autobahn.. ist evtl. was für nach schneekönigin.

2022-11-25 00:00 UTC, wolfgangroese commented on src/app/features/musician-profile-dialog/musician-instruments/musician-instruments.component.html
> +  <header *ngIf="isNew; else editHeader ">
Bin gerade krass overwhelmed, was du für Dinge siehst.. hammer! Never ever wäre mir das aufgefallen.. grandios! danke!

2022-11-25 00:33 UTC, wolfgangroese commented on src/assets/i18n/appointments/fr.json
> +
Schlampigkeit ,-) Gesäubert ,-)

2022-11-25 18:26 UTC, VILLAN3LL3 commented on src/app/features/mupro/profiles/profiles.component.html
> +                      pTooltip="{{ 'musician-profile-dialog.LEVEL_ASSESSMENT_PERFORMER' | translate }}"
ok

2022-11-25 18:53 UTC, VILLAN3LL3 approved these changes, later dismissed

2022-11-25 21:23 UTC, merged