Language menu Anpassungen
orso-co/Orso.Arpa.Web pull request #43
Opened 2021-03-09 17:26 UTC by kypu

- Accept Language Interceptor hinzugefügt
- Language Service hinzugefügt
- Sprachauswahl in User Menu außer bei Login und Register Seiten
- Language in localStorage gespeichert damit es nicht zurückgesetzt wird wenn man die Seite neulädt
- Header in der Mobile Version ohne Wilkommenstext

2021-03-09 18:30 UTC, VILLAN3LL3 requested changes
Kleinigkeiten. Kannst ja schauen, ob du es so lassen oder ändern willst.

2021-03-09 18:30 UTC, VILLAN3LL3 commented on src/app/components/shell/topbar/topbar.component.scss
> +      display: none;
primeng bietet für sowas auch eigene Klassen an, siehe https://www.primefaces.org/primeng/showcase/#/primeflex/display

2021-03-09 18:30 UTC, VILLAN3LL3 commented on src/app/components/shell/topbar/topbar.component.ts
> +    this.langChangeListener = this.translate.onLangChange.subscribe((event: LangChangeEvent) => {
Kann man so machen. Aber anstatt this.translate.instant kann man auch .get machen und darauf subscriben

2021-03-09 18:30 UTC, VILLAN3LL3 commented on src/app/services/language.service.ts
> +    this.localStorage = window.localStorage;
du kannst den localStorage einfach mit localStorage aufrufen ohne window

2021-03-09 18:30 UTC, VILLAN3LL3 commented on src/app/services/language.service.ts
> +    console.log(existingLang);
wird das console.log noch gebraucht?

2021-03-09 19:23 UTC, kypu commented on src/app/services/language.service.ts
> +    console.log(existingLang);
nein!

2021-03-09 19:23 UTC, kypu commented on src/app/services/language.service.ts
> +    this.localStorage = window.localStorage;
geändert

2021-03-09 19:24 UTC, kypu commented on src/app/components/shell/topbar/topbar.component.scss
> +      display: none;
geändert

2021-03-09 19:25 UTC, kypu commented on src/app/components/shell/topbar/topbar.component.ts
> +    this.langChangeListener = this.translate.onLangChange.subscribe((event: LangChangeEvent) => {
Ich habe das jetzt so gelassen; wenn man den Text direkt in der html mit | async anzeigt könnte ich das so verstehen aber ich bin mir nicht sicher wie ich das als teil der Menu machen soll

2021-03-10 09:48 UTC, VILLAN3LL3 approved these changes

2021-03-10 16:27 UTC, merged