ngx-translate integration
orso-co/Orso.Arpa.Web pull request #5
Opened 2021-01-25 13:56 UTC by MichaelSpielmann

1. ngx-translate first setup
2. add elements for register/password reset

2021-01-25 17:49 UTC, VILLAN3LL3 requested changes

2021-01-25 17:49 UTC, VILLAN3LL3 commented on src/app/app.component.ts
> +    translate.addLangs(['de', 'ed']);
Meinst du mit "ed" vielleicht "en"? :)

2021-01-25 21:10 UTC, MichaelSpielmann commented on src/app/app.component.ts
> +    translate.addLangs(['de', 'ed']);
Ja, danke fürs genaue Hinschauen :-)

2021-01-26 06:21 UTC, VILLAN3LL3 approved these changes

2021-01-26 06:34 UTC, merged