add validation check for inputs and prepare auth
orso-co/Orso.Arpa.Web pull request #8
Opened 2021-01-27 06:57 UTC by MichaelSpielmann

1. added validation check for input fields 
2. prepare authentification

2021-01-27 09:48 UTC, wolfgangroese reviewed
Schaut hübsch aus! Da warst ja schon früh fleißig heute morgen. Ich weiß halt nicht, ob ich einfach "approven" kann, da ich mich noch nicht für soooo kompetent halte, mögliche Fehler oder so zu entdecken. Ich kann einigermaßen nachvollziehen, was du genau gemacht hast und für mich schaut das gut aus, soweit ich das beurteilen kann. Soll ich einfach trotzdem mal "approven" ? ,-)

2021-01-27 09:49 UTC, wolfgangroese commented
ups, jetzt erst gesehen, daß "checks failed"..

2021-01-27 10:34 UTC, VILLAN3LL3 requested changes

2021-01-27 10:34 UTC, VILLAN3LL3 commented on src/app/login/login.component.ts
> +  loginFormGroup = new FormGroup ({
Warum initialisierst du die FormGroup doppelt? Einmal hier und einmal im ngOnInit

2021-01-27 10:34 UTC, VILLAN3LL3 commented on src/app/services/auth.service.ts
> +    localStorage.removeItem(LOCAL_STORAGE_TOKEN_KEY);
Nur zur Info: Ich nehme in den kommenden Tagen eine Backend-Anpassung live, bei der ein Logout-Endpunkt dazukommt, sowie ein RefreshToken-Endpunkt. Da muss dann dieser Service ggf. nochmal angepasst werden

2021-01-27 10:34 UTC, VILLAN3LL3 commented on src/app/login/login.component.ts
> +          Validators.pattern('(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&].{6,}')
warum verwendest du hier nicht das oben deklarierte password pattern?

2021-01-27 10:34 UTC, VILLAN3LL3 commented on src/app/login/login.component.ts
> +  password: '(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&].{6,}'
Das könnte zukünftig noch ein bisschen userfreundlicher gestaltet werden, um dem User die einzelnen Aspekte anzeigen zu können. Inspiration: https://github.com/quarano/quarano-application/blob/develop/frontend/libs/shared/util-forms/src/lib/validators/password.validator.ts

2021-01-27 10:34 UTC, VILLAN3LL3 commented on src/app/login/login.component.html
> +            type="button"
Wenn du den type rausnimmst, hat der Button automatisch den type "submit". Dann kannst du den Click Handler weglassen und stattdessen oben in <form> ein ngSubmit einfügen: `(ngSubmit)="submit()"`

2021-01-27 10:34 UTC, VILLAN3LL3 commented on src/app/login/login.component.html
> +            <input type="password" placeholder="{{ 'PASSWORD' | translate }}" pPassword [feedback]=false formControlName="password">
Wenn Validierungsfehler auftreten, sollten die dem User auch angezeigt werden

2021-01-27 13:40 UTC, VILLAN3LL3 commented
Noch ein Hinweis: Wenn du deine Branches und Commits mit ARPA-<JiraItemNr> beginnen lässt, dann werden sie automatisch mit den entsprechenden Items in Jira verknüpft

2021-01-27 16:02 UTC, MichaelSpielmann commented on src/app/login/login.component.ts
> +  loginFormGroup = new FormGroup ({
Danke für den Hinweis, wird geändert. War noch ein Überbleibsel vom Experiemtieren.

2021-01-27 16:03 UTC, MichaelSpielmann commented on src/app/login/login.component.ts
> +          Validators.pattern('(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&].{6,}')
auch wieder so eine Laiche :-) -> geändert

2021-01-28 15:59 UTC, VILLAN3LL3 commented on src/app/login/login.component.ts
> +  password: '(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&].{6,}'
Ich resolve das mal, war ja nur ein Tipp

2021-01-28 17:05 UTC, VILLAN3LL3 approved these changes

2021-01-28 17:05 UTC, VILLAN3LL3 commented on src/app/login/login.component.html
> +            <input type="password" placeholder="{{ 'PASSWORD' | translate }}" pPassword [feedback]=false formControlName="password">
wird nach Rücksprache mit Michael separat umgesetzt

2021-01-28 17:05 UTC, VILLAN3LL3 commented on src/app/services/auth.service.ts
> +    localStorage.removeItem(LOCAL_STORAGE_TOKEN_KEY);
Nach RS mit Michael wird das separat umgesetzt

2021-01-28 17:05 UTC, merged